// Layout component panel
export const FETCH_ITEMS_TO_LAYOUT_ACTIONS = 'FETCH_ITEMS_TO_LAYOUT_ACTIONS';
export const REMOVE_ITEM_LAYOUT_ACTIONS = 'REMOVE_ITEM_LAYOUT_ACTIONS';
export const UPDATE_ITEMS_LAYOUT_ACTIONS = 'UPDATE_ITEMS_LAYOUT_ACTIONS';
export const REMOVE_ALL_ITEMS_LAYOUT_ACTIONS = 'REMOVE_ALL_ITEMS_LAYOUT_ACTIONS';

// components panel
export const UPDATE_COMPONENT_ITEM = 'UPDATE_COMPONENT_ITEM';
export const CHOOSE_COMPONENT_ITEM = 'CHOOSE_COMPONENT_ITEM';
export const SUBMIT_CODE_LINES = 'SUBMIT_CODE_LINES';