export const ADD_ITEM_TO_LAYOUT_ACTIONS = 'ADD_ITEM_TO_LAYOUT_ACTIONS';
export const FETCH_ITEMS_TO_LAYOUT_ACTIONS = 'FETCH_ITEMS_TO_LAYOUT_ACTIONS';
export const REMOVE_ITEM_LAYOUT_ACTIONS = 'REMOVE_ITEM_LAYOUT_ACTIONS';
export const SAVE_ITEMS_LAYOUT_ACTIONS = 'SAVE_ITEMS_LAYOUT_ACTIONS';
export const REMOVE_ALL_ITEMS_LAYOUT_ACTIONS = 'REMOVE_ALL_ITEMS_LAYOUT_ACTIONS';